### ISSUE TITLE
Feature Services to enable Sync

### ISSUE THREAD

**Issue by mripp** [NWFWMD-IT/Hydrologic-Monitoring-Project#116]
While publishing the feature service [Hydrologic Monitoring Field](https://geoservices.nwfwmd.state.fl.us/portal/home/item.html?id=d8a690ddca904a938380911efb95f015) I attempted to publish with sync enabled but received an error

![Image](https://github.com/NWFWMD-IT/Hydrologic-Monitoring-Project/assets/55856222/52bbbcca-32c9-4bf9-aa17-04470473474e)

**Comment by mmannion** [comment]
I've been researching this message and have a few questions. To summarize:
- I'm not sure whether we need to do anything
- If we do need to do something, I don't understand:
  - Why
  - How _Replica Tracking_ works


# Do we need to do anything?

I don't think so, because:

1. Per the screenshot above, the message is a warning, not an error. I think we can still publish the service with a warning.
1. We are not using this feature service in a bidirectional ArcGIS Enterprise / Online collaboration. We are using it for synchronizing to the offline clients Field Maps and Survey123. Per the message's [documentation page](https://pro.arcgis.com/en/pro-app/latest/help/sharing/analyzer-warning-messages/24127-syncing-bidirectionally-not-supported-nonversioned-archive-enabled-without-replica-tracking.htm), under _Solutions_, the first bullet states:

> If you do not intend to use this feature service in a bidirectional collaboration, you don't have to do anything.

3. Per the documentation [Prepare data for use in offline feature services](https://pro.arcgis.com/en/pro-app/latest/help/data/geodatabases/overview/prepare-feature-layer-data-for-offline.htm#ESRI_SECTION1_C08B3EED25CB4918BEB167E09175C2DB), _Scenario 1: Versioning is not required_
  - Scenario 1 describes our use case (nonversioned + archiving) but does not include enabling Replica Tracking as a requirement
  - Replica Tracking is listed as a requirement when using branch versioning (Scenario 2) but we are not using branch versioning.

That said, we may want to enable Replica Tracking; I just don't know if we have to and, if not, what factors would motivate us to enable/disable that optional functionality.


# How does Replica Tracking work?

Regarding the following documentation:
- [Enable Replica Tracking](https://pro.arcgis.com/en/pro-app/latest/tool-reference/data-management/enable-replica-tracking.htm) geoprocessing tool
  - This page describes how to enable Replica Tracking, but does not describe what it is or how it works

- [Introduction to distributed data](https://pro.arcgis.com/en/pro-app/latest/help/data/geodatabases/overview/introduction-to-distributed-data.htm#ESRI_SECTION1_CAEE457B708A433CB3F63BEF5E676374), section _Take a map offline with feature service sync capability_
  - This page describes the concept of a _Feature Service Replica_ but does not elaborate on how it is implemented

- [24127 warning message](https://pro.arcgis.com/en/pro-app/latest/help/sharing/analyzer-warning-messages/24127-syncing-bidirectionally-not-supported-nonversioned-archive-enabled-without-replica-tracking.htm)
  - In the _Solutions_ section, the second bullet describes the effect of locks on the _Enable Replica Tracking_ tool, specifically regarding "adding the fields it needs to the feature class", but does not describe the fields

I will experiment with enabling Replica Tracking and look for changes to the test feature class and the geodatabase metadata. In the meantime, I have three questions for @mripp and @rkircher:

1. **QUESTION**: Are there other resources (e.g. doc, UC presentations) that describe in more detail what Replica Tracking is and how it is implemented?
1. **QUESTION**: Is Replica Tracking required for our use case?
1. **QUESTION**: If not, do we want to enable it anyway and, if so, why?

**Comment by mripp** [comment]
This message is appearing when publishing the feature service as Sync Enabled. The feature service must be configured with sync enabled in order to bring the feature service offline in both ArcGIS Field Maps and ArcGIS Survey123. 

![image](https://github.com/NWFWMD-IT/Hydrologic-Monitoring-Project/assets/55856222/9ca6da63-5011-425f-933b-3d9a1536ee97)

I went ahead and published the feature service with the warning. It appears the feature service did publish successfully and the feature service REST appears to have sync enabled: https://geoservices.nwfwmd.state.fl.us/server/rest/services/Hydro/Hydrologic_Monitoring_Field/FeatureServer
![image](https://github.com/NWFWMD-IT/Hydrologic-Monitoring-Project/assets/55856222/2d42703f-3273-4544-9b50-4d37f717a353)

Upon opening the Field Maps configuration it is confirmed that all layers are sync enabled. As shown by the green check mark 
![image](https://github.com/NWFWMD-IT/Hydrologic-Monitoring-Project/assets/55856222/58f6baae-c1ec-448d-8248-857ead40e5e5)

Additional troubleshooting will be needed since upon opening and adding an offline map an error occured
![image](https://github.com/NWFWMD-IT/Hydrologic-Monitoring-Project/assets/55856222/0d7aca7c-8f4f-4082-a1fe-ca31d85cae59)
![image](https://github.com/NWFWMD-IT/Hydrologic-Monitoring-Project/assets/55856222/f76b1322-0511-402f-a43f-f70e31457e04)
![image](https://github.com/NWFWMD-IT/Hydrologic-Monitoring-Project/assets/55856222/73981085-28cc-4b07-9a8c-659730bc4b6e)

**Comment by SarahNWF** [comment]
Robert to reach out to Michael to diagnose issue.

**Comment by mripp** [comment]
Michael, Robert, and Morgan met to diagnose issue
- Confirmed the data can be brought offline in ArcGIS Pro
- Issue is related to the basemap
- Morgan created a new map and reconfigured the pop-ups, which has removed the "Layers Error" warning
- Next step is to add the Streets basemap as an offline layer and add this to the map
