### ISSUE TITLE
Field Names Need to be Unique Across Data Model

### ISSUE THREAD

**Issue by mripp** [NWFWMD-IT/Hydrologic-Monitoring-Project#12]
Survey123 throws an error whenever it detects two of the same column names in the xlsx. We will have to make the following fields uniquely different

**Temperature Measurement Table**
MeasureDate --> MeasureDate_temp or TemperatureMeasureDate etc..
ReadingType --> ReadingType_temp
SerialNumber --> SerialNumber_temp
ManualLevel --> ManualLevel_temp
SensorLevel --> SensorLevel_temp

**Groundwater Measurement**
MeasureDate --> 
ReadingType --> 
ManualLevel -->
WaterLevel -->
SensorLevel --> 
SensorAdjustmentAmount --> 
SensorAdjusted --> 
SensorAdjustmentException --> 
SensorAdjustmentDate --> 

**Conductivity Measurement Table**
MeasureDate -->
ReadingType -->
SerialNumber -->
ManualLevel -->
SensorLevel -->
SensorAdjustmentAmount -->
SensorAdjusted -->
SensorAdjustmentException -->
SensorAdjustmentDate -->

**StageMeasurement**
ManualLevel --> StageManualLevel   (used to calculate WaterLevel, used to calculate difference threshold)
WaterLevel --> StageWaterLevel   (used to calculate difference threshold)
SensorLevel --> StageSensorLevel   (used to calculate SensorAdjsutmentAmount)
SensorAdjusted --> StageSensorAdjusted   (Used in relevant statement to show/hide sensor adjustment fields)

**DataLogger**
SerialNumber -->
Comments -->

**VisitStaff**
Name  -->

**Comment by mmannion** [comment]
Per James Tedrick, Survey123 Product Manager, we can use Survey123 with tables that have columns with the same name. This information is poorly/not documented, so a summary and some supporting references follow.


## ENVIRONMENT

- The survey uses a feature service that includes multiple tables
- The tables are related by geodatabase Relationship Classes
  - The Origin table is referenced in the main section of the survey
  - The Destination tables are referenced in repeat sections of the survey
- Some tables contain columns with the same name (e.g. `StageMeasurement.ManualLevel`, `GroundwaterMeasurement.ManualLevel`) 


## SURVEY123 BEHAVIOR

- When designing a survey using an XLSForm in Excel, Column B, "name", represents two things:
  - The unique name of each survey question
  - The unqualified physical name of the target column in which the question's answer is stored

In a simple example, we have two tables - `HYDRO.Site` and `HYDRO.Asset` - the former being the Origin and the latter being the Destination. Both tables include a column called `Name`.

Publishing a feature service for these tables > creating a survey from the service > editing the survey in Excel yields the following:

![Image](https://user-images.githubusercontent.com/4367508/192121277-16581927-f4be-46f4-b71f-f43e00677ba0.png)

Observe that:
- The `HYDRO.Site.Name` column is in the main section
- The `HYDRO.Asset.Name` column is in the repeat section
- Both names are highlighted in red because they are not unique

Despite this warning, we are able to publish and use the survey normally.

More importantly, this behavior is supported. Per James ([2022-09-22_email_from_james_tedrick.pdf](https://github.com/NWFWMD-IT/Hydrologic-Monitoring-Project/files/9639711/2022-09-22_email_from_james_tedrick.pdf)):

>There is not an absolute requirement that all column names be unique.

We do, however, need to make accommodations when working with these columns in survey calculations.



### SURVEY CALCULATIONS

- When columns with the same name exist in the same survey, we cannot use the `#{Name}` syntax to reference them in calculations
  - In our test case above the survey question name "Name" is ambiguous
- It is not supported to modify the survey question name in order to disambiguate it - it must be the exact, unqualified name of the column in the underlying feature service (and, in turn, in the underlying database table)

Per James ([2022-09-23_email_from_james_tedrick.pdf](https://github.com/NWFWMD-IT/Hydrologic-Monitoring-Project/files/9639716/2022-09-23_email_from_james_tedrick.pdf)):
- We can uniquely identify each question in a calculation by its XML path, such as:
  - `/Survey_Title/Name` (main section)
  - `/Survey_Title/HYDRO.Asset/Name` (repeat section)

(Note that for the Excel workbook named "Survey Title.xlsx", we need to replace the space with an underscore in the XML path.)

So, we can concatenate the two `Name` values, for example, using the calculation:

`concat(/Survey_Title/Name, /Survey_Title/HYDRO.Asset/Name)`

Per a [reference](https://docs.getodk.org/form-logic/#xpath-paths) that James provided:

> The `${}` and XPath notations can be mixed freely.



# ACTION ITEMS

- [ ] @mripp: Verify that the XML path syntax works in our production survey

If successful:

- [ ] @mripp: Update all survey calculations that include duplicate column names to use XML path syntax

If unsuccessful:

- [ ] @mmannion: Update the data model to use unique column names for columns used in calculations

Reassigning to @mripp to test this solution with the survey. If it fails, please add comments to describe your findings and reassign back to @mmannion to update the database.

**Comment by mripp** [comment]
Got it! I will test this XML path calculation with the Stage and Groundwater related tables

I am also attaching a screenshot of the example XLSX form from James 
![2022-09-23 XLSX Example from James](https://user-images.githubusercontent.com/55856222/192397880-4709c1b0-b684-4d5a-9898-581619597bd9.png)

**Comment by mripp** [comment]
@mmannion Confirmed that the XML path syntax works in both calculations and relevant statements in the form.
