### ISSUE TITLE
Remove "Is this Stage used for Discharge"

### ISSUE THREAD

**Issue by mripp** [NWFWMD-IT/Hydrologic-Monitoring-Project#159]
Remove - all questions in the section will show up. The user will know to skip certain questions if its discharge

![Image](https://github.com/NWFWMD-IT/Hydrologic-Monitoring-Project/assets/55856222/d988e28b-5347-46a0-aea8-7610232510d5)

- [x] @mmannion to delete field `StageMeasurement.IsDischarge` from database
- [x] @mripp to remove field and logic in survey

**Comment by mmannion** [comment]
@kprice-TLH would you please confirm that there is no back office need for the IsDischarge flag before we remove it from the database?

I recall that this information was used for more than showing/hiding controls in the survey, but I'm not confident in my recollection.

**Comment by mmannion** [comment]
- `IsDischarge` is not needed for back-office because we can tell from `LocationVisit.DischargeRecordStart/End`  timestamps which of potentially multiple stage measurements is associated with the discharge

- Survey does not need this because we will show discharge-related fields all the time, and users will know whether to skip them

**Comment by mripp** [comment]
Confirmed DB change in Survey123 - can be closed
