### ISSUE TITLE
Fix battery level behavior

### ISSUE THREAD

**Issue by mmannion** [NWFWMD-IT/Hydrologic-Monitoring-Project#176]
- [x] When _Battery Needs Replaced?_ is "Yes" AND _Battery Level_ OK AND _Battery Replaced_ is "No", then in _Logger File_ section, battery exception widgets need to be displayed
- [x] Ideally, display battery exception fields at in _Battery_ section (beginning of Location Visit) and the _Logger Files_ section (end of Location Visit)
- Fix _Battery Level_ input field to:
  - [x] Recognize all low voltages (e.g. 10.0 triggers low warning but 9.00 does not)
  - [x] Disallow non-numeric characters
  - [x] Add maximum value - 100
  - [x] Change constraint to note / warning

**Comment by SarahNWF** [comment]
In the Survey123 excel file, there wasn't a field in the logger file section for a "Battery Exception" question. Instead of copying the question and having it come up twice in the survey, maybe we move it?
Changes I've made have been done in the dev copy of the survey.
-Moved the battery replacement exceptions to the Logger File section of the survey. It triggers if the user selects:
Battery Section       Is the Battery DOA? Yes
                               Was the Battery replaced? No

                               Is the Battery DOA? No
                               Battery Needs Replaced? Yes


Logger File Section Was the battery replaced? No (Question pops up if user selected yes for battery needs replaced in the section above).

**Comment by SarahNWF** [comment]
Now the message "The data logger battery will need to be replaced at the end of the site visit" will pop-up in the battery section and the logger file section if user inputs a value that is less than the low voltage value associated with the site.
