### ISSUE TITLE
Troubleshoot: Publishing from Survey123 Failed

### ISSUE THREAD

**Issue by mripp** [NWFWMD-IT/Hydrologic-Monitoring-Project#35]
Attempted to publish a survey as a hosted feature layer but publishing failed. I assume this is because we are unable to make hosted feature layers in general. 

This should be resolved when I publish the survey on top of the existing geodatabase layer

![Image](https://user-images.githubusercontent.com/55856222/194909875-20b8395e-f239-4703-92ac-c30e5f42601e.png)

**Comment by mmannion** [comment]
Could you post the full text of the _Critical_ error message shown in the screenshot above?

I'm heading out to an appointment for a few hours, but will look at this in more detail when I get back.

FWIW, within the last week or two, I accidentally published a hosted feature layer instead of referencing an existing geodatabase feature class. I subsequently found some setting for disabling the ability to upload data when publishing - but I can't remember where it was. I was working on my local development server for sure, but I don't recall whether I changed that setting in Pro, Portal, or Server. Anyway, if this rings a bell, it might be worth checking the NWFWMD servers to see if that same setting is disabled.

**Comment by mripp** [comment]
@mmannion Closing this issue out. I was able to publish the a survey today to the Portal. For some reason yesterday I couldn't create a hosted feature layers so now that that issue is gone survey123 connect doesn't have the error anymore.

**Comment by mmannion** [comment]
I moved this back from `Finished` to `Done` so we can review during the next team meeting
