### ISSUE TITLE
Troubleshoot: Submitting Survey Error

### ISSUE THREAD

**Issue by mripp** [NWFWMD-IT/Hydrologic-Monitoring-Project#37]
I am receiving an error when trying to submit an entry via the Survey123 Field App to an existing hosted feature layer (id:b5dbdd53fbe2450e99b56dc6006e066a) in the NWFWMD Portal.

This service was published from the XML file

![Image](https://user-images.githubusercontent.com/55856222/195456912-4bd0ca65-4a4b-422e-bc37-0fd69157b65d.png)

Note: This error is not occurring in ArcGIS Online on the same service and survey configuration 

When I go to the REST endpoint of the feature service there isn't a Creation Date Field or Creation By assigned. These 2 fields might need to be assigned in to EGDB in order for the survey to work. We will not know until that layer is ready to use

![Image](https://user-images.githubusercontent.com/55856222/195458509-fd5ff30b-b345-475f-83eb-0f4195780b48.png)

**Comment by mripp** [comment]
When I go to the REST endpoint of the feature service there isn't a Creation Date Field Assigned


![Image](https://user-images.githubusercontent.com/55856222/195458509-fd5ff30b-b345-475f-83eb-0f4195780b48.png)

**Comment by mripp** [comment]
Example of how the REST endpoint should be configured. The survey works with this hosted feature service (id: ed8a491dd6f74540a4929cbd77cff8be)


![Image](https://user-images.githubusercontent.com/55856222/195461923-494027b8-2dfc-4bc3-ad17-3dac978a9e1b.png)

**Comment by mmannion** [comment]
Are you able to exclude _Creation Date Field_ and _Creator Field_ from the survey?

We determined during the initial Lands model development a few years back that NWFWMD didn't need to retain the creation date/user as separate fields; if anyone needed this info, they could look at the last edited date/user in the archive history.

If Survey123 allows excluding these, we should do so in order to stick with the established standard. If there's no workaround, we can add them as an exception here.

**Comment by mmannion** [comment]
Per 2022-10-31 team meeting, @mripp confirmed that issue did not occur with enterprise geodatabase tables.
