### ISSUE TITLE
Add inventory to survey

### ISSUE THREAD

**Issue by mmannion** [NWFWMD-IT/Hydrologic-Monitoring-Project#50]
Add read-only inventory information to survey so users can verify what they observe during location visits:

- `DataLogger.Type`
- `DataLogger.SerialNumber`
- `Sensor.Type`
- `Sensor.SerialNumber`

If the inventory is incorrect, user will log a location issue, with `LocationIssue.Type` set to "Incorrect inventory".

**Comment by mripp** [comment]
@mmannion 
I will need some more information for this in order to configure in Survey123 since this isn't in the workflow diagram right now. 

I am imaging when they get to the Location and start the Location Visit the user will be able to view a list of 4 fields you mention. 

To clarify can there be multiple Data Loggers and multiple Sensors per each location?

**Comment by mmannion** [comment]
Per @kprice-TLH:
- There can be multiple Data Loggers and Sensors at each Location
- User does not need to confirm which sensors are connected to which logger, just which equipment is present (or absent) at the Location

**Comment by mmannion** [comment]
To do:
- Move inventory to proper position in survey based on position in workflow

**Comment by mripp** [comment]
Because the Data Logger & Sensor is related to the Location and not the Location Visit we can't directly place the Inventory information in the Location Visit Repeat. We have 3 options to take

1) Keep the prompt 'Is Inventory records correct?' where is is. The user would have to scroll up to the Data Logger/Sensor & Measuring Point repeats to check the inventory and then go to the Issue repeat to record the issue. 

2) Move the prompt 'Is Inventory records correct?' to the beginning of the location visit. The user will see the Data Logger/Sensor & Measuring Point first thing and can record if there is an issue in the repeat below. 

![Image](https://user-images.githubusercontent.com/55856222/201533899-4cfe0010-0ad9-4b51-a7ca-f63e904f9fca.png)

**Comment by mripp** [comment]
Discussed on 11/14

@mmannion will add a field for 'Are the inventory records correct?' in the Location Visit Table. 
@mripp will keep this question before the DataLogger/Sensor but will pass the value to the field in the Location Visit Table
@mripp will add a photo for MeasuringPoints which will display when they open up the survey

**Comment by mmannion** [comment]
Sorry; didn't realize this was outstanding because it wasn't assigned to me.

- **QUESTION**: Do we still need to store an explicit yes/no in the database to reflect whether inventory records are correct?

This ticket is pretty old, so I don't know what the state of the workflow model was like when it was created. From looking at the current draft, I'm thinking that we don't need to add another column. Reason being, the current workflow (_Assess Location_ phase) has survey and user record inventory problems as a Location Issue early in the visit:

![Image](https://user-images.githubusercontent.com/4367508/225178486-64a9361b-3053-4a62-80d2-561086916d2f.png)

If this is modeled correctly, the "Are the inventory records correct?" question would be in the survey only - the result of which would be to prompt/reveal/etc. the relevant controls for recording an inventory issue if one exists. Therefore, we wouldn't store an explicit yes/no for the question, but rather would or would not have a Location Issue record.

This may be incorrect, though - we might want to force the user to choose a yes/no value. We do that in many other places, just to confirm that they actually checked something, and didn't just skip it.

Review this at the next team meeting.

**Comment by mmannion** [comment]
OK, that makes sense to me. Thanks for explaining.

I'd like to ask @kprice-TLH to make a final decision for us on Monday.

The inventory question is an outlier, in that we don't force the user to confirm the inventory with a yes/no choice. In most cases, we're interpreting an empty value to mean that the user didn't get to that question, whereas a 'Yes' or 'No' confirms that they actually did something, even if they didn't find anything wrong. I don't know whether the inventory question is modeled different intentionally, or if we just overlooked it previously.

**Comment by mmannion** [comment]
Per 2023-03-17 call, confirmed with @kprice-TLH that we do not need to store the answer. Closing this ticket.

**Comment by mmannion** [comment]
Added target annotation to workflow diagram. This was previously in the model, per the LocationVisit screenshot immediately above, but wasn't being populated anywhere in the workflow.


![Image](https://user-images.githubusercontent.com/4367508/226490467-b828a002-5fc4-4393-aced-11ee0fd5d872.png)
