### ISSUE TITLE
Determine if Survey123 allows overwriting a value

### ISSUE THREAD

**Issue by mmannion** [NWFWMD-IT/Hydrologic-Monitoring-Project#7]
Example workflow:
- Capture initial battery voltage
- Change battery
- Capture new battery voltage

Question: Can the final voltage overwrite the initial voltage, or do we need to store two rows?

**Comment by mmannion** [comment]
Later in the 2022-05-31 team meeting we discussed for another property just scrolling back up in the survey and editing a previously-entered value. That might work here, as well.

To clarify, the question above is about having two different Survey123 controls editing the same attribute in the feature service.

**Comment by SarahNWF** [comment]
Response from Morgan:

•	Can we configure the survey to export certain fields? Example: t[here](https://doc.arcgis.com/en/survey123/desktop/create-surveys/esricustomcolumns.htm#GUID-036FFF12-0CD5-437C-9FC7-4B47A89D8292) is a question that is answered via pull data – the answer influences which groups show up in the survey. We don’t really need that answer in the export table, is there a way to leave that out once the survey is submitted?

**_You can set the ‘bind::esri:fieldType’ to null. This will effectively use the value in the survey but when the survey gets submitted nothing gets written to the feature service. 
Documentation can be found here_**

•	Can two different  rows answer the same attribute? Example: A questions asks for battery level, user takes some measurements and has to record battery level again, can the latter battery level record override the original from earlier in the survey? (I’m pretty sure I asked this before and the answer was no)

**_This should be doable in the survey. I attached an example of what I would do – essentially you would record the battery level in two different places but ultimately just record it once in the feature service. If I am not understanding the workflow we can talk more about this._** 

•	Can we set up the survey export so that certain fields go to different layers / tables in the feature service? 

**_The only way to set up a survey to export to multiple layers or table is with Repeat. Each set of Repeats will be saved in a separate layer or table. I would recommend looking at the Nested Repeats survey template as an example_**

**Comment by mripp** [comment]
There are multiple fields that appear in the beginning of the survey and then again at the end. In order for this to work the values will be collected in each section as NULL bind::esri:fieldType and then an if statement will store the latest recorded value. 

- LocationVisit.BatteryReplaced
- LocationVisit.BatteryReplacementException
- LocationVisit.BatteryReplacementDate
- LocationVisit.BatteryVoltage

Question: Does Time Adjustment (TA) workflow get completed for the 2nd Data Logger section?

**Comment by mmannion** [comment]
From 2022-10-31 team meeting, will have one battery section that writes directly to the database fields. If users need to update at the end of the workflow, they will scroll back up. If scrolling becomes too burdensome during testing, we can look at ways to streamline subsequently.
