### ISSUE TITLE
Remove ADVM Battery

### ISSUE THREAD

**Issue by mripp** [NWFWMD-IT/Hydrologic-Monitoring-Project#95]
Since the last ADVM battery was removed from the field Katie requested that we remove the ADVM battery workflow. Per [email](https://github.com/NWFWMD-IT/Hydrologic-Monitoring-Project/files/11523456/email.pdf) from 4/18

- [x] @mmannion to remove ADVM battery fields `LocationVisit.ADVMBatteryDOA`, `LocationVisit.ADVMBatteryCondition`, `LocationVisit.ADVMBatteryVoltage` , `LocationVisit.ADVMBatteryReplaced`,  `LocationVisit.ADVMBatteryReplacementDate`, `LocationVisit.ADVMBatteryReplacementException`, `LocationVisit.ADVMBatteryReplacementComments`
- [x] @mmannion to update workflow
- [x] @mripp to update survey

**Comment by mmannion** [comment]
# Marking Pre-removal Repo State Using a Tag

Create a historical marker in repo commit history before removing ADVM features using a git _tag_. 

It appears that we need to create > sync tags using the `git` command line, after which they'll appear in GitHub web. Git supports two types of tags, _lightweight_ and _annotated_, as described in the [doc](https://git-scm.com/book/en/v2/Git-Basics-Tagging). We should use an annotated tag, both for the reasons described in the doc, and because GitHub web will show the tag message instead of the underlying commit message when browsing tags.

To create and sync a tag:
- `git tag -a beforeRemovingADVMBattery -m "Last commit before removing ADVM battery features"`
- `git push origin --tags`

After that, we can navigate to that tag in the repo via the web UI:

![Image](https://user-images.githubusercontent.com/4367508/234120170-e279d7c5-1bf5-4cf4-879a-4f088090f47d.png)

(Use the "View all tags" link at bottom of the dropdown to see the tag message)

**Comment by mmannion** [comment]
- Created git tag `beforeRemovingADVMBattery` to mark last repo commit containing ADVM battery feature
- Removed column `Location.HasADVMBattery`
- Removed `LocationVisit` columns:
  - `LocationVisit.ADVMBatteryDOA`
  - `LocationVisit.ADVMBatteryCondition`
  - `LocationVisit.ADVMBatteryVoltage` 
  - `LocationVisit.ADVMBatteryReplaced`
  - `LocationVisit.ADVMBatteryReplacementDate`
  - `LocationVisit.ADVMBatteryReplacementException`
  - `LocationVisit.ADVMBatteryReplacementComments`
- Updated data loader accordingly

**Comment by mripp** [comment]
mripp removed all columns in the survey
